### ISSUE TITLE
Not working if some features are enabled on server

### ISSUE THREAD

**Issue by Dr-Electron** [fpierfed/keepalive#1]
Hi,

First of all, great job 👍 

But we had some problems with your bot because the server used some features that aren't detected as valid by pincer.
Some where already added in newer commits but not released yet. And one was added by myself here: https://github.com/Pincer-org/Pincer/pull/431

Maybe you should think about using the main branch of pincer or at least use a newer commit in the meantime?

**Comment by fpierfed** [comment]
Awesome that you find the bot useful! The code does indeed rely on the latest released version of Pincer. It might make sense to use main...
